book/urls.py
from django.urls import path
from .views import *

app_name = 'book'

urlpatterns = [
    path('', all_books, name = 'all_books'),
    path('create/', CreateBook.as_view(), name = 'create_book'),
    path('delete/<int:id>', delete, name = 'delete_book'),
    path('update/<int:id>', UpdateBook.as_view(), name = 'update_book')
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('authentication.urls')),
    path('orders/', include('order.urls')),
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('', all_orders, name = 'all_orders'),
    path('create/', CreateOrder.as_view(), name = 'create_order'),
    path('delete/<int:id>', delete, name = 'delete_order'),
    path('update/<int:id>', UpdateOrder.as_view(), name = 'update_order')
]

order/models.py
from django.db import models, DataError, IntegrityError

from authentication.models import CustomUser
from author.models import Author
from book.models import Book
import datetime


class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    end_at = models.DateTimeField(null=True)
    plated_end_at = models.DateTimeField()

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        # return str(self.to_dict())[1:-1]
        return f"{self.user} {self.book}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'
    def to_dict(self):

        return {
            'id': self.id,
            'user': self.user,
            'book': self.book,
            'created_at': str(self.created_at),
            'end_at': str(self.end_at) if self.end_at else self.end_at,
            'plated_end_at': str(self.plated_end_at)
        }

    @staticmethod
    def create(user, book, plated_end_at):

        order = Order(user=user, book=book, plated_end_at=plated_end_at)
        if book.count <= len([order for order in Order.get_not_returned_books() if order.book.id == book.id]):
            return
        try:
            order.save()
            return order
        except (IntegrityError, AttributeError, DataError, ValueError) as err:
            # print(err)
            # LOGGER.error("Wrong attributes or relational integrity error")
            pass

    @staticmethod
    def get_by_id(order_id):

        try:
            user = Order.objects.get(id=order_id)
            return user
        except Order.DoesNotExist:
            pass

    def update(self, plated_end_at=None, end_at=None):
        if plated_end_at:
            self.plated_end_at = plated_end_at
        if end_at:
            self.end_at = end_at
        self.save()

    @staticmethod
    def get_all():
        all_order = list(Order.objects.all())
        return all_order

    @staticmethod
    def get_not_returned_books():
        orders = [order for order in Order.get_all() if order.end_at is None]
        return orders

    @staticmethod
    def delete_by_id(order_id):
        """
        :param user_id: an id of a user to be deleted
        :type user_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """

        try:
            user = Order.objects.get(id=order_id)
            user.delete()
            return True
        except Order.DoesNotExist:
            # LOGGER.error("User does not exist")
            pass
        return False

order/forms.py
from django import forms
from .models import Order, Book, CustomUser
from authentication.models import CustomUser 
from django.core.exceptions import ValidationError
from django.forms.widgets import NumberInput

class DateInput(forms.DateTimeInput):
    input_type = 'date'

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        # user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
        # book = models.ForeignKey(Book, on_delete=models.CASCADE)
        # created_at = models.DateTimeField(auto_now_add=True, editable=False)
        # end_at = models.DateTimeField(null=True)
        fields = ['user', 'book', 'plated_end_at']
        widgets = {'plated_end_at': DateInput()}
        #user =  forms.ModelChoiceField(CustomUser.objects.all(), empty_label = None, to_field_name = 'user')
        # widgets = {
        #     'first_name': forms.TextInput(attrs = {'class': 'form-control'}),
        #     'last_name': forms.TextInput(attrs = {'class': 'form-control'}),
        #     'email': forms.EmailInput(attrs = {'class': 'form-control'})
        # }

    def clean(self):
        # user =  self.cleaned_data['user']
        # book = self.cleaned_data['book']
        # created_at = self.cleaned_data['created_at']
        # end_at = self.cleaned_data['end_at']
        # if Order.objects.filter(first_name = first_name).filter(last_name = last_name).count():
        #     raise ValidationError("Such user has been already created")
        # if Order.objects.filter(email = email).count():
        #     raise ValidationError("User with such email has been already created")
        return self.cleaned_data

class UpdateOrderForm(OrderForm):
    
    def clean(self):
        user =  self.cleaned_data['user']
        book = self.cleaned_data['book']
        plated_end_at = self.cleaned_data['plated_end_at']
        return self.cleaned_data

order/views.py
from django.shortcuts import render, redirect
from .models import Order
from django.views.generic import View
from .forms import OrderForm, UpdateOrderForm

def all_orders(request):
    list_of_orders = Order.get_all()

    return render(request, "order\\all_orders.html", {"list_of_orders": list_of_orders})

def delete(request, id):
    Order.delete_by_id(id)
    return redirect('order:all_orders')

class CreateOrder(View):
    
    def get(self, request):
        form = OrderForm()
        return render(request, 'order\\create_order_form.html', {'form': form})
    
    def post(self, request):
        bound_form = OrderForm(request.POST)
        if bound_form.is_valid():
            new_order = bound_form.save()
            return redirect('order:all_orders')
        return render(request, 'order\\create_order_form.html', {'form': bound_form})

class UpdateOrder(View):
    def get(self, request, id):
        order = Order.get_by_id(id)
        form = UpdateOrderForm(instance=order)
        return render(request, 'order\\update_order_form.html', {'form': form, "order": order})
    def post(self, request, id):
        order = Order.get_by_id(id)
        bound_form = UpdateOrderForm(request.POST, instance=order)
        if bound_form.is_valid():   
            bound_form.save()
            return redirect('order:all_orders')
        print('-'*90)
        return render(request, 'order\\update_order_form.html', {'form': bound_form})

order/templates/order/all_orders.html
{%extends 'order\\base.html'%}
{%block main%}
<h4>		
	{%if list_of_orders%}
		{%for order in list_of_orders%}
			<ul>
				<div class ='form-group col-md-6'>
					<li>{{order.book.name}} {{order.user.first_name}} {{order.user.last_name}} {{order.plated_end_at}}
						<a href = {% url "order:delete_order" order.pk%} class = 'btn btn-primary'>Delete</a>
						<a href = {% url "order:update_order" order.pk%} class = 'btn btn-primary'>Update</a>
					</li>
				</div>
			</ul>
		{%endfor%}
	{%else%}There is nothing 
	{%endif%}
</h4>
<h5><a href = {% url "order:create_order" %}>Create order</a></h5>

{%endblock%}

order/templates/order/base.html
<!DOCTYPE html>

<html lang="en">

<head>

	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
	integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">




</head>

<body>

{% block main %}{% endblock %}
<body>

</html>

order/templates/order/create_order_form.html
{%extends 'order\\base.html'%}
{% block main %}
<div class ='form-group col-md-2'>
<form action="{%url 'order:create_order'%}", method = "post">
    {% csrf_token %}
    {% for field in form %}
        <div сlass = 'form-group mb-2'>
            {{field.label}}
            {{field}}
        </div>   
    {% endfor %}
    {% if form.errors %}
        <div class = 'alert alert-danger'>{{form.non_field_errors}}{{form.errors}}</div>
    {% endif %}
    <button type="submit" class = 'btn btn-primary'>Create</button>
</form>
</div>


{% endblock %}

order/templates/order/update_order_form.html
{%extends 'order\\base.html'%}
{% block main %}
<div class ='form-group col-md-2'>
<form action="{%url 'order:update_order' order.pk%}", method = "post">
    {% csrf_token %}
    {% for field in form %}
        <div сlass = 'form-group mb-2'>
            {{field.label}}
            {{field }}
        </div>   
    {% endfor %}
    {% if form.errors %}
        <div class = 'alert alert-danger'>{{form.non_field_errors}}</div>
    {% endif %}
    <button type="submit" class = 'btn btn-primary'>Update</button>
</form>
</div>

{% endblock %}