author/urls.py
from django.urls import path
from .views import *

app_name = 'author'

urlpatterns = [
    path('', all_authors, name = 'all_authors'),
    path('create/', CreateAuthor.as_view(), name = 'create_author'),
    path('delete/<int:id>', delete, name = 'delete_author'),
    path('update/<int:id>', UpdateAuthor.as_view(), name = 'update_author')
]

book/urls.py
from django.urls import path
from .views import *

app_name = 'book'

urlpatterns = [
    path('', all_books, name = 'all_books'),
    path('create/', CreateBook.as_view(), name = 'create_book'),
    path('delete/<int:id>', delete, name = 'delete_book'),
    path('update/<int:id>', UpdateBook.as_view(), name = 'update_book')
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('authentication.urls')),
    path('orders/', include('order.urls')),
]

author/models.py
from django.db import models, IntegrityError, DataError


class Author(models.Model):
    """
        This class represents an Author. \n
        Attributes:
        -----------
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes last name of the author
        type surname: str max_length=20
        param patronymic: Describes middle name of the author
        type patronymic: str max_length=20

    """

    name = models.CharField(blank=True, max_length=20)
    surname = models.CharField(blank=True, max_length=20)
    patronymic = models.CharField(blank=True, max_length=20)

    def __str__(self):
        """
        Magic method is redefined to show all information about Author.
        :return: author id, author name, author surname, author patronymic
        """
        return str(self.to_dict())[1:-1]
        # return f"{self.name} {self.surname}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Author object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'

    @staticmethod
    def get_by_id(author_id):
        """
        :param author_id: SERIAL: the id of a Author to be found in the DB
        :return: author object or None if a user with such ID does not exist
        """
        try:
            user = Author.objects.get(id=author_id)
            return user
        except Author.DoesNotExist:
            pass
            # LOGGER.error("User does not exist")

    @staticmethod
    def delete_by_id(author_id):
        """
        :param author_id: an id of a author to be deleted
        :type author_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """

        try:
            author = Author.objects.get(id=author_id)
            author.delete()
            return True
        except Author.DoesNotExist:
            # LOGGER.error("User does not exist")
            pass
        return False

    @staticmethod
    def create(name, surname, patronymic):
        """
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes surname of the author
        type surname: str max_length=20
        param patronymic: Describes patronymic of the author
        type patronymic: str max_length=20
        :return: a new author object which is also written into the DB
        """
        author = Author(name=name, surname=surname, patronymic=patronymic)
        try:
            author.save()
            return author
        except (IntegrityError, AttributeError, DataError):
            # LOGGER.error("Wrong attributes or relational integrity error")
            pass

    def to_dict(self):
        """
        :return: author id, author name, author surname, author patronymic
        :Example:
        | {
        |   'id': 8,
        |   'name': 'fn',
        |   'surname': 'mn',
        |   'patronymic': 'ln',
        | }
        """

        return {
            'id': self.id,
            'name': self.name,
            'surname': self.surname,
            'patronymic': self.patronymic
        }

    def update(self,
               name=None,
               surname=None,
               patronymic=None):
        """
        Updates author in the database with the specified parameters.\n
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes surname of the author
        type surname: str max_length=20
        param patronymic: Describes patronymic of the author
        type patronymic: str max_length=20
        :return: None
        """

        if name:
            self.name = name
        if surname:
            self.surname = surname
        if patronymic:
            self.patronymic = patronymic
        try:
            from django.db import transaction
            with transaction.atomic():
                self.save()
        except:
            pass

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all authors
        """
        all_users = Author.objects.all()
        return all_users

author/forms.py
from django import forms
from .models import Author
from django.core.exceptions import ValidationError


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'surname', 'patronymic']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'patronymic': forms.TextInput(attrs={'class': 'form-control'})
        }

    def clean(self):
        name = self.cleaned_data['name']
        surname = self.cleaned_data['surname']
        patronymic = self.cleaned_data['patronymic']
        if Author.objects.filter(name=name).filter(surname=surname).count():
            raise ValidationError("Such author has been already created")
        if Author.objects.filter(patronymic=patronymic).count():
            raise ValidationError("User with such patronymic has been already created")
        return self.cleaned_data


class UpdateAuthorForm(AuthorForm):

    def clean(self):
        name = self.cleaned_data['name']
        surname = self.cleaned_data['surname']
        patronymic = self.cleaned_data['patronymic']
        return self.cleaned_data

author/views.py
from django.shortcuts import render, redirect
from .models import Author
from django.views.generic import View
from .forms import AuthorForm, UpdateAuthorForm


def all_authors(request):
    list_of_authors = Author.get_all()
    return render(request, "author\\all_authors.html", {"list_of_authors": list_of_authors})


def delete(request, id):
    Author.delete_by_id(id)
    return redirect('author:all_authors')


class CreateAuthor(View):

    def get(self, request):
        form = AuthorForm()
        return render(request, 'author\\create_author_form.html', {'form': form})

    def post(self, request):
        bound_form = AuthorForm(request.POST)
        if bound_form.is_valid():
            new_user = bound_form.save()
            return redirect('author:all_authors')
        return render(request, 'author\\create_author_form.html', {'form': bound_form})


class UpdateAuthor(View):
    def get(self, request, id):
        author = Author.get_by_id(id)
        form = UpdateAuthorForm(instance=author)
        return render(request, 'author\\update_author_form.html', {'form': form, "author": author})

    def post(self, request, id):
        author = Author.get_by_id(id)
        bound_form = UpdateAuthorForm(request.POST, instance=author)
        if bound_form.is_valid():
            bound_form.save()
            return redirect('author:all_authors')
        print('-' * 90)
        return render(request, 'author\\update_author_form.html', {'form': bound_form})

author/templates/author/all_authors.html
{%extends 'author\\base.html'%}
{%block main%}
<h3>
	{%if list_of_authors%}
		{%for author in list_of_authors%}
			<ul>
				<div class ='form-group col-md-6'>
					<li>{{author.name}} {{author.surname}}
						<a href = {% url "author:delete_author" author.pk%} class = 'btn btn-primary'>Delete</a>
						<a href = {% url "author:update_author" author.pk%} class = 'btn btn-primary'>Update</a>
					</li>
				</div>
			</ul>
		{%endfor%}
	{%else%}There is nothing
	{%endif%}
</h3>
<h5><a href = {% url "author:create_author" %}>Create author</a></h5>

{%endblock%}

author/templates/author/base.html
<!DOCTYPE html>

<html lang="en">

<head>

	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
	integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<title>Authors</title>

</head>

<body>

{% block main %}{% endblock %}
<body>

</html>

author/templates/author/create_author_form.html
{%extends 'author\\base.html'%}
{% block main %}
<div class ='form-group col-md-2'>
<form action="{%url 'author:create_author'%}", method = "post">
    {% csrf_token %}
    {% for field in form %}
        <div сlass = 'form-group mb-2'>
            {{field.label}}
            {{field}}
        </div>
    {% endfor %}
    {% if form.errors %}
        <div class = 'alert alert-danger'>{{form.non_field_errors}}</div>
    {% endif %}
    <button type="submit" class = 'btn btn-primary'>Create</button>
</form>
</div>

{% endblock %}

author/templates/author/update_author_form.html
{%extends 'author\\base.html'%}
{% block main %}
<div class ='form-group col-md-2'>
<form action="{%url 'author:update_author' author.pk%}", method = "post">
    {% csrf_token %}
    {% for field in form %}
        <div сlass = 'form-group mb-2'>
            {{field.label}}
            {{field}}
        </div>
    {% endfor %}
    {% if form.errors %}
        <div class = 'alert alert-danger'>{{form.non_field_errors}}</div>
    {% endif %}
    <button type="submit" class = 'btn btn-primary'>Update</button>
</form>
</div>

{% endblock %}