book/urls.py
from django.urls import path
from .views import *

app_name = 'book'

urlpatterns = [
    path('', all_books, name = 'all_books'),
    path('create/', CreateBook.as_view(), name = 'create_book'),
    path('delete/<int:id>', delete, name = 'delete_book'),
    path('update/<int:id>', UpdateBook.as_view(), name = 'update_book')
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('authentication.urls')),
    path('orders/', include('order.urls')),
]

book/models.py
from django.db import models, IntegrityError, DataError

from author.models import Author


class Book(models.Model):
    """
        This class represents an Author. \n
        Attributes:
        -----------
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
    """

    name = models.CharField(blank=True, max_length=128)
    description = models.TextField(blank=True)
    count = models.IntegerField(default=10)
    authors = models.ManyToManyField(Author, related_name='books')

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        # return str(self.to_dict())[1:-1]
        return f"{self.name}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'

    @staticmethod
    def get_by_id(book_id):
        """
        :param book_id: SERIAL: the id of a Book to be found in the DB
        :return: book object or None if a book with such ID does not exist
        """
        try:
            user = Book.objects.get(id=book_id)
            return user
        except Book.DoesNotExist:
            pass
            # LOGGER.error("User does not exist")

    @staticmethod
    def delete_by_id(book_id):
        """
        :param book_id: an id of a book to be deleted
        :type book_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """

        try:
            book = Book.objects.get(id=book_id)
            book.delete()
            return True
        except Book.DoesNotExist:
            # LOGGER.error("User does not exist")
            pass
        return False

    @staticmethod
    def create(name, description, count=10, authors=None):
        """
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
        :return: a new book object which is also written into the DB
        """
        book = Book(name=name, description=description, count=count)
        try:
            book.save()
            if authors is not None:
                for author in authors:
                    book.authors.add(author)
            book.save()
            return book
        except (IntegrityError, AttributeError, DataError):
            # LOGGER.error("Wrong attributes or relational integrity error")
            pass

    def to_dict(self):
        """
        :return: book id, book name, book description, book count, book authors
        :Example:
        | {
        |   'id': 8,
        |   'name': 'django book',
        |   'description': 'bla bla bla',
        |   'count': 10',
        |   'authors': []
        | }
        """

        return {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'count': self.count,
            'authors': [author.id for author in self.authors.all()]
        }

    def update(self, name=None, description=None, count=None):
        """
        Updates book in the database with the specified parameters.\n
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        :return: None
        """

        if name:
            self.name = name
        if description:
            self.description = description
        if count:
            self.count = count
        self.save()

    def add_authors(self, authors):
        """
        Add  authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """

        for author in authors:
            self.authors.add(author)
        self.save()

    def remove_authors(self, authors):
        """
        Remove authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        for author in authors:
            self.authors.remove(author)
        self.save()

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all books
        """
        all_users = Book.objects.all()
        return list(all_users)

book/forms.py
from django import forms
from .models import Book
from django.core.exceptions import ValidationError


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'description', 'count']
        # widgets = {
        #     'name': forms.CharField(attrs={'class': 'form-control'}),
        #     'description': forms.TextInput(attrs={'class': 'form-control'}),
        #     'count': forms.IntegerField(attrs={'class': 'form-control'})
        #     # 'authors': forms.TextInput(attrs={'class': 'form-control'})
        # }

    def clean(self):
        name = self.cleaned_data['name']
        description = self.cleaned_data['description']
        count = self.cleaned_data['count']
        if Book.objects.filter(name=name).filter(description=description).count():
            raise ValidationError("Such author has been already created")
        if Book.objects.filter(count=count).count():
            raise ValidationError("User with such patronymic has been already created")
        return self.cleaned_data


class UpdateBookForm(BookForm):

    def clean(self):
        name = self.cleaned_data['name']
        description = self.cleaned_data['description']
        count = self.cleaned_data['count']
        return self.cleaned_data

book/views.py
from django.shortcuts import render, redirect
from .models import Book
from django.views.generic import View
from .forms import BookForm, UpdateBookForm


def all_books(request):
    list_of_books = Book.get_all()
    return render(request, "book\\all_books.html", {"list_of_books": list_of_books})


def delete(request, id):
    Book.delete_by_id(id)
    return redirect('book:all_books')


class CreateBook(View):

    def get(self, request):
        form = BookForm()
        return render(request, 'book\\create_book_form.html', {'form': form})

    def post(self, request):
        bound_form = BookForm(request.POST)
        if bound_form.is_valid():
            new_book = bound_form.save()
            return redirect('book:all_books')
        return render(request, 'book\\create_book_form.html', {'form': bound_form})


class UpdateBook(View):
    def get(self, request, id):
        book = Book.get_by_id(id)
        form = UpdateBookForm(instance=book)
        return render(request, 'book\\update_book_form.html', {'form': form, "book": book})

    def post(self, request, id):
        book = Book.get_by_id(id)
        bound_form = UpdateBookForm(request.POST, instance=book)
        if bound_form.is_valid():
            bound_form.save()
            return redirect('book:all_books')
        print('-' * 90)
        return render(request, 'book\\update_book_form.html', {'form': bound_form})

book/templates/book/all_books.html
{%extends 'book\\base.html'%}
{%block main%}
<h3>
	{%if list_of_books%}
		{%for book in list_of_books%}
			<ul>
				<div class ='form-group col-md-6'>
					<li>{{book}}
						<a href = {% url "book:delete_book" book.pk%} class = 'btn btn-primary'>Delete</a>
						<a href = {% url "book:update_book" book.pk%} class = 'btn btn-primary'>Update</a>
					</li>
				</div>
			</ul>
		{%endfor%}
	{%else%}There is nothing
	{%endif%}
</h3>
<h5><a href = {% url "book:create_book" %}>Create book</a></h5>

{%endblock%}

book/templates/book/base.html
<!DOCTYPE html>

<html lang="en">

<head>

	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
	integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<title>Books</title>

</head>

<body>

{% block main %}{% endblock %}
<body>

</html>

book/templates/book/create_book_form.html
{%extends 'book\\base.html'%}
{% block main %}
<div class ='form-group col-md-2'>
<form action="{%url 'book:create_book'%}", method = "post">
    {% csrf_token %}
    {% for field in form %}
        <div сlass = 'form-group mb-2'>
            {{field.label}}
            {{field}}
        </div>
    {% endfor %}
    {% if form.errors %}
        <div class = 'alert alert-danger'>{{form.non_field_errors}}{{form.errors}}</div>
    {% endif %}
    <button type="submit" class = 'btn btn-primary'>Create</button>
</form>
</div>


{% endblock %}

book/templates/book/update_book_form.html
{%extends 'book\\base.html'%}
{% block main %}
<div class ='form-group col-md-2'>
<form action="{%url 'book:update_book' book.pk%}", method = "post">
    {% csrf_token %}
    {% for field in form %}
        <div сlass = 'form-group mb-2'>
            {{field.label}}
            {{field}}
        </div>
    {% endfor %}
    {% if form.errors %}
        <div class = 'alert alert-danger'>{{form.non_field_errors}}</div>
    {% endif %}
    <button type="submit" class = 'btn btn-primary'>Update</button>
</form>
</div>

{% endblock %}